url: ""
baseurl: "" 

# Site settings
title: NextFaze
email: contact@nextfaze.com
description: The Internet HQ of NextFaze, a delightful software development shop in Adelaide, Australia. Specialising in mobile apps - iOS, Android and Web Development!

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/nextfaze
  - title: github
    url: https://github.com/NextFaze
  - title: bitbucket
    url: https://bitbucket.org/nextfaze
  - title: facebook
    url: https://www.facebook.com/nextfaze

# Postal address (add as many lines as necessary)
address:
  - line: 28 O'Connell Street
  - line: North Adeliade, South Australia
  - line: 5006 Australia

# Build settings
markdown: kramdown
permalink: pretty